os: 
  - osx
  # - windows
language: node_js
node_js:
  - 12
cache:
  yarn: true

addons:
  homebrew:
    packages:
    - pkg-config  
    - cairo
    - pango
    - libpng
    - jpeg
    - giflib
    - librsvg

script:
  - cd renderer
  - yarn install
  - cd ..
  - yarn install
  - yarn run pack:$TRAVIS_OS_NAME