name: Package-And-Release-App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Pack@${{ matrix.os }}&Node${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node Env
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Renderer Node Modules
        run: |
          cd extensions
          yarn install
          cd ../workspace-extension
          yarn install
          cd ../replayer
          yarn install
          cd ../renderer
          yarn install
      - name: Install App Node Modules
        run: yarn install
      - name: Package for Windows
        if: runner.os == 'Windows'
        run: |
          yarn run publish:windows
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Package For OSX
        if: runner.os == 'macOS'
        run: |
          yarn run publish:osx
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Package For Linux
        if: runner.os == 'Linux'
        run: |
          yarn run publish:linux
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}